### ISSUE TITLE
feat: initialise not-found middle-ware

### ISSUE THREAD

**Issue by sboy99** [sboy99/libu-server#3]
- Enable not-found middle-ware at the last to handle unknown routes

**Comment by dhruvdabhi101** [comment]
> Enable not-found middle-ware at the last to handle unknown routes

Okay. I'll try to do it. I'm quite new in MERN. So Help from you will be appreciated. Once you assign me the issue I'll start working. ☺️

**Comment by sboy99** [comment]
Yeah obviously, if you feel any doubts then feel free to ask me. I am putting what you need to do exactly to enable unknown routes handling.
First create a middleware `notFound.middleware.ts` then inside it send simple bad request and as a response message send 'route doesn't exist ' 
Next import the middleware in the app and initialize it in the app, that's it. Just give it a try and thank you.

**Comment by dhruvdabhi101** [comment]
can you tell me resource to get started with typescript and express ?

**Comment by sboy99** [comment]
> can you tell me resource to get started with typescript and express ?

DM me on twitter !!
